// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RhLslJqn5bnCo_f2lrL3TV0cjL5YLxU',
    appId: '1:931531270856:web:4451aff754a0b403dd53fd',
    messagingSenderId: '931531270856',
    projectId: 'e-connect-bbc5a',
    authDomain: 'e-connect-bbc5a.firebaseapp.com',
    storageBucket: 'e-connect-bbc5a.appspot.com',
    measurementId: 'G-2QTVYKEXDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe065RH2ryGcFGlEFXT8vK3SquAU7D5JA',
    appId: '1:931531270856:android:467886d3a8015593dd53fd',
    messagingSenderId: '931531270856',
    projectId: 'e-connect-bbc5a',
    storageBucket: 'e-connect-bbc5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQlWKiLTPCiq3gAIXi2O6Qn_Rcrd_xgoc',
    appId: '1:931531270856:ios:ec04e63ee9aa400cdd53fd',
    messagingSenderId: '931531270856',
    projectId: 'e-connect-bbc5a',
    storageBucket: 'e-connect-bbc5a.appspot.com',
    iosClientId: '931531270856-2vq2it5e6r85dlaqhtc3cvt4ngtei694.apps.googleusercontent.com',
    iosBundleId: 'com.example.eConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQlWKiLTPCiq3gAIXi2O6Qn_Rcrd_xgoc',
    appId: '1:931531270856:ios:e119398c5e5e4ef4dd53fd',
    messagingSenderId: '931531270856',
    projectId: 'e-connect-bbc5a',
    storageBucket: 'e-connect-bbc5a.appspot.com',
    iosClientId: '931531270856-2s4gqm0qu83gte3q7cfcepdsc9f8eu0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.eConnect.RunnerTests',
  );
}
